name: "CI"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 28.1
          - 27.2
          - 26.3
          - 25.3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Set up Cask
        uses: conao3/setup-cask@master
      - name: Compile
        run: |
          make compile
      # - name: Test
      #   run: |
      #     make test
